[package]
name = "qtlib"
version = "0.2.0"
authors = ["MrLynch", "Forge"]
edition = "2018"

[lib]
name = "zecwalletlite"
crate-type = ["staticlib"]

[dependencies]
libc = "0.2.58"
lazy_static = "1.4.0"
zecwalletlitelib = { git="https://github.com/piratenetwork/piratewallet-light-cli", rev="ddada7676bbd1f86d9e8fe220102235b0410e79e" }
