name: Build PirateWallet-Lite

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  # Fix set-output deprecation warnings
  GITHUB_ACTIONS_DEPRECATION_WARNINGS: false

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
          
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc
          
      - name: Build
        shell: cmd
        run: |
          mkdir -p res/libs
          cd res/libzecwalletlite
          cargo build --lib --release
          
          REM Check both possible extensions and copy the file that exists
          if exist "target\release\libpiratewalletlite.a" (
            copy "target\release\libpiratewalletlite.a" "..\..\res\libs\"
          ) else if exist "target\release\piratewalletlite.lib" (
            copy "target\release\piratewalletlite.lib" "..\..\res\libs\libpiratewalletlite.a"
          ) else if exist "target\release\qtlib.lib" (
            copy "target\release\qtlib.lib" "..\..\res\libs\libpiratewalletlite.a"
          ) else (
            dir "target\release" /s
            exit /b 1
          )
          
          cd ..\..
          
          REM Setup Visual Studio environment
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          
          qmake piratewallet-lite-mingw.pro CONFIG+=release
          nmake

  build-linux-x86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libgl1-mesa-dev libsodium-dev \
            mesa-common-dev libglu1-mesa-dev
          
      - name: Set up Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          host: 'linux'
          target: 'desktop'
          
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: Build
        run: |
          set -x  # Enable debug output
          mkdir -p res/libs
          cd res/libzecwalletlite
          
          # Set environment variables
          export SODIUM_LIB_DIR=/usr/lib/x86_64-linux-gnu
          
          # Build the Rust library
          cargo build --lib --release
          
          # Copy the library (with fallback to find it if not in expected location)
          cp target/release/libpiratewalletlite.a ../../res/libs/ || {
            echo "Library not found at expected location, searching for it:"
            find target -name "*.a" -o -name "*.so"
            find target -type f -size +100k
            exit 1
          }
          
          cd ../..
          # Ensure Qt is on the path
          export PATH="${Qt5_DIR}/bin:$PATH"
          qmake piratewallet-lite.pro CONFIG+=release
          make -j$(nproc) V=1

  build-linux-aarch64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libgl1-mesa-dev libsodium-dev \
            gcc-aarch64-linux-gnu g++-aarch64-linux-gnu binutils-aarch64-linux-gnu \
            gperf python3-pip pkg-config autoconf libtool
          
      - name: Set up Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          host: 'linux'
          target: 'desktop'
          
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-unknown-linux-gnu
          
      - name: Build dependencies
        run: |
          set -x  # Enable debug output
          BUILD=$(./depends/config.guess)
          HOST="aarch64-linux-gnu"
          # Retry the build a few times if it fails (sometimes transient errors occur)
          for i in {1..3}; do
            make -C ./depends HOST="$HOST" -j$(nproc) V=1 && break || {
              echo "Attempt $i failed. Retrying..."
              sleep 5
            }
          done
          
          # Check if the build was successful
          if [ ! -d "./depends/aarch64-linux-gnu" ]; then
            echo "Dependencies build failed. Showing some debugging info:"
            find ./depends -name "config.log" -exec echo "=== {} ===" \; -exec tail -n 100 {} \;
            exit 1
          fi
          
      - name: Build
        run: |
          set -x  # Enable debug output
          mkdir -p res/libs
          cd res/libzecwalletlite
          
          # Set environment variables for cross-compilation
          export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc
          export CC_aarch64_unknown_linux_gnu=aarch64-linux-gnu-gcc
          export CXX_aarch64_unknown_linux_gnu=aarch64-linux-gnu-g++
          export AR_aarch64_unknown_linux_gnu=aarch64-linux-gnu-ar
          
          # Build the Rust library
          cargo build --lib --release --target aarch64-unknown-linux-gnu
          
          # Copy the library (with fallback to find it if not in expected location)
          cp target/aarch64-unknown-linux-gnu/release/libpiratewalletlite.a ../../res/libs/ || {
            echo "Library not found at expected location, searching for it:"
            find target -name "*.a" -o -name "*.so"
            find target/aarch64-unknown-linux-gnu -type f -size +100k
            exit 1
          }
          
          cd ../..
          export PATH="$(pwd)/depends/aarch64-linux-gnu/bin:$PATH"
          export QT_STATIC="$(pwd)/depends/aarch64-linux-gnu"
          
          # Print directory contents to debug
          ls -la "$QT_STATIC/bin" || true
          
          # Check if qmake exists
          if [ ! -f "$QT_STATIC/bin/qmake" ]; then
            echo "qmake not found at expected location. Searching for it:"
            find depends -name qmake
            exit 1
          fi
          
          "$QT_STATIC"/bin/qmake piratewallet-lite.pro CONFIG+=release
          make -j$(nproc) V=1

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          brew install libsodium qt@5
          brew link qt@5 --force
          # Install create-dmg if it's needed for packaging
          brew install create-dmg
          
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
          
      - name: Build
        run: |
          set -x  # Enable debug output

          # Make sure we know where libsodium is
          SODIUM_PREFIX=$(brew --prefix libsodium)
          echo "Libsodium prefix: $SODIUM_PREFIX"
          ls -la $SODIUM_PREFIX/lib/
          
          # Export library paths
          export LIBRARY_PATH="$SODIUM_PREFIX/lib:$LIBRARY_PATH"
          export CPATH="$SODIUM_PREFIX/include:$CPATH"
          export LDFLAGS="-L$SODIUM_PREFIX/lib $LDFLAGS"
          export CPPFLAGS="-I$SODIUM_PREFIX/include $CPPFLAGS"
          
          # Create library directory
          mkdir -p res/libs
          
          # Build libpiratewalletlite
          cd res/libzecwalletlite
          export SODIUM_LIB_DIR="$SODIUM_PREFIX/lib"
          cargo build --lib --release
          
          # Find and copy the library
          if [ -f "target/release/libpiratewalletlite.a" ]; then
            cp target/release/libpiratewalletlite.a ../../res/libs/
          else
            find target -name "*.a" -o -name "*.dylib"
            ls -la target/release
            exit 1
          fi
          
          cd ../..
          
          # Set up Qt
          export PATH="$(brew --prefix qt@5)/bin:$PATH"
          
          # Create a symbolic link to libsodium in res/libs
          ln -sf "$SODIUM_PREFIX/lib/libsodium.dylib" res/libs/
          ln -sf "$SODIUM_PREFIX/lib/libsodium.a" res/libs/
          
          # Build with explicit paths
          qmake \
            "LIBS += -L$SODIUM_PREFIX/lib -lsodium" \
            "INCLUDEPATH += $SODIUM_PREFIX/include" \
            piratewallet-lite.pro CONFIG+=release
          
          make -j$(sysctl -n hw.ncpu)
          
          # Create DMG (if needed)
          mkdir -p artifacts
          if [ -d "PirateWallet-Lite.app" ]; then
            create-dmg --volname "PirateWallet-Lite" --volicon "res/logo.icns" \
            --window-pos 200 120 --icon "PirateWallet-Lite.app" 200 190 \
            --app-drop-link 600 185 --window-size 800 400 \
            artifacts/macOS-piratewallet-lite.dmg PirateWallet-Lite.app || true
          fi

  build-macos-arm64:
    runs-on: macos-latest-xlarge # This uses M1 Mac runners
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          brew install libsodium
          
      - name: Set up Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          host: 'mac'
          target: 'desktop'
          
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
          
      - name: Build
        run: |
          # Use the build-mac-arm.sh script
          export APP_VERSION="1.0.11"
          export PREV_VERSION="1.0.10"
          bash utils/build-mac-arm.sh 